import Navbar from "@/components/shared/navbar";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div className="bg-[url('/starry_background.jpg')] bg-repeat text-white min-h-screen">
            {children}
        </div>
      </body>
    </html>
  );
}
