import { Sidebar } from "@/components/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import backgroundImage from "@/public/space.webp"; // keep this import for webpack

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      className="flex h-screen bg-[url('/space.webp')] bg-repeat bg-cover"
      style={{
        backgroundRepeat: "repeat",
        backgroundImage: "url('/space.webp')",
        backgroundSize: "auto",
      }}
    >
      <Sidebar />
      <div className="flex-1 flex flex-col overflow-hidden bg-transparent">
        {/* <Header /> */}
        <main className="flex-1 overflow-y-auto p-6 bg-transparent text-white">
          {children}
        </main>
      </div>
    </div>
  );
}
